In [1]:


##  TYPE CASTING



In [2]:
import numpy as np
from sklearn import random_projection

In [11]:
rng = np.random.RandomState(0)
X = rng.rand(10, 2000)
X = np.array(X)
X.dtype

dtype('float64')

In [12]:
X = np.array(X, dtype = "float32")
X.dtype

dtype('float32')

In [13]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
X_new.dtype

dtype('float64')

In [18]:
from sklearn import datasets
from sklearn.svm import SVC

In [20]:
iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data, iris.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [23]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [25]:


##  REFITTING AN UPDATING PARAMETERS



In [34]:
import numpy as np
from sklearn.svm import SVC

In [38]:
rng = np.random.RandomState(0)
X = rng.rand(100, 10)
y = rng.binomial(1, 0.5, 100)
X_test = rng.rand(5, 10)

In [40]:
clf = SVC()
clf.set_params(kernel="linear").fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [36]:
clf.set_params(kernel="rbf").fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [1]:


##  MULTICLASS VERSUS MULTILABEL FITTING



In [10]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

In [11]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0,0,1,1,2]

In [12]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [13]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
from sklearn.preprocessing import MultiLabelBinarizer

In [15]:
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])